# Default configuration - base configuration shared by all environments

server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "3306"
  user: "gin_boilerplate"
  password: "gin_boilerplate"
  dbname: "gin_boilerplate"

jwt:
  secret: "your-secret-key-change-this-in-production"
  expire_time: 24  # Token expiration time (hours)
