# Development environment configuration - overrides corresponding config in default.yaml

server:
  mode: "debug"

database:
  host: "localhost"
  port: "3306"
  user: "gin_boilerplate"
  password: "gin_boilerplate"
  dbname: "gin_boilerplate"

jwt:
  secret: "dev-secret-key-for-development"
  expire_time: 72  # Development environment has longer token validity
