# Production environment configuration - overrides corresponding config in default.yaml

server:
  mode: "release"

database:
  host: "localhost"
  port: "3306"
  user: "gin_boilerplate"
  password: "gin_boilerplate"
  dbname: "gin_boilerplate"

jwt:
  secret: "change-this-to-a-strong-secret-key-in-production"
  expire_time: 24
